### ISSUE TITLE
Open to adding `source_up_global` option? 

### ISSUE THREAD

**Issue by genehack** [zimbatm/direnv#154]
I've got a use case where it would be useful for direnv to act like `source_up` was in every `.envrc` file[1]. Ideally, this would just be a `~/.direnvrc` option, something like `source_up_global`. The mechanism I'm envisioning would be to find all `.direnv` files, searching upwards, and then apply them in turn from topmost to bottommost. That way a "lower" directory could override a "higher" one, which seems like what Least Surprise would dictate.

Is this something that you'd be open to getting a patch for? I'm willing to do the work, I just want to make sure you're receptive to the idea. 

[1]: My use case is this: I have distinct trees for my "work" and "personal" projects.  I'd like to have `work/.direnv` set `GIT_AUTHOR` and friends to my work identity, and `projects/.direnv` set them to my personal identity, without having to set them in each individual project-level `.direnv`, and without having to put `source_up` in each individual project-level `.direnv`.

**Comment by zimbatm** [comment]
Hi @genehack , I don't mind adding new commands to the stdlib.

My own guideline is that I start by adding commands to my own `~/.direnvrc` and when I find them to be generally useful and stable I would move them to the stdlib. I can also see how that command could be useful to others.

In terms of naming, `source_up_all` might be better.

**Comment by genehack** [comment]
Ah, I was thinking this was something that would need to be done at a 'tool' level, not at the 'stdlib' level. I'll play around with adding it to the ~/.direnvrc and see if I can get that to work. 

Thanks!

**Comment by zimbatm** [comment]
Yeah it's fine to add new internal commands as well. I had to do that for `expand_path` for example because there is no good cross-platform shell or system command to do that.

Here you can see how the stdlib command just forwards to direnv: https://github.com/zimbatm/direnv/blob/master/stdlib.sh#L52
And here is the implementation: https://github.com/zimbatm/direnv/blob/master/cmd_expand_path.go . The `Private: true` flag hides it from the normal help output.

**Comment by genehack** [comment]
So, thinking about this more, I think this is less a new command, and more like a global configuration flag affecting the code in https://github.com/zimbatm/direnv/blob/master/cmd_export.go. 

Another (probably better) way to implement what I want would be to have `direnv hook $SHELL` take an option flag, like `--load-all`, which would cause it to output a different subcmd in the hook, something like `direnv export_all $SHELL`.

Essentially, I want a global way to _always_ force multiple `.direnv` files to "layer" upwards, without having to put `source_up()` in each one of them.

**Comment by zimbatm** [comment]
If a command is executed in the `~/.direnvrc` it's executed whenever a
.envrc is loaded, in effect making it a global config.

Here is a direnvrc skeleton to get you started:

```
source_up_all() {
  # your code here
  echo Hi
}

source_up_all
```
