### ISSUE TITLE
Not working with Fish?

### ISSUE THREAD

**Issue by tfaoro** [zimbatm/direnv#164]
Hello,

I'm running direnv v2.6.0 with Fish and simply trying to set some variables.

.envrc is:
```
set -x PATH /opt/chefdk/bin /Users/tmf/.chefdk/gem/ruby/2.1.0/bin /opt/chefdk/embedded/bin /Users/tmf/bin /usr/local/bin /opt/local/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin
set -x GEM_ROOT /opt/chefdk/embedded/lib/ruby/gems/2.1.0
set -x GEM_HOME /Users/tmf/.chefdk/gem/ruby/2.1.0
set -x GEM_PATH /Users/tmf/.chefdk/gem/ruby/2.1.0 /opt/chefdk/embedded/lib/ruby/gems/2.1.0
```
When I change into this directory, direnv spits out a bunch of information:
```
➤ cd nrdecor-chef
direnv: loading .envrc
++ set -x GEM_ROOT /opt/chefdk/embedded/lib/ruby/gems/2.1.0
++ set -x GEM_HOME /Users/tmf/.chefdk/gem/ruby/2.1.0
++ set -x GEM_PATH /Users/tmf/.chefdk/gem/ruby/2.1.0 /opt/chefdk/embedded/lib/ruby/gems/2.1.0
+ popd
+ popd
+ /usr/local/Cellar/direnv/2.6.0/bin/direnv dump
```
I wouldn't mind that, but then it doesn't actually make any of the changes to my env:
```
➤ env | grep PATH
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```
Am I missing something obvious here? Is there a specific format for .envrc? Do I need to escape the -x somehow?

**Comment by zimbatm** [comment]
Hi Tony, the .envrc file is actually loaded in bash and the environnent
changes are then exported to your shell.

**Comment by tfaoro** [comment]
Well, aren't I a noobie's uncle.

Thanks!

**Comment by zimbatm** [comment]
To be fair I think the doc could explain that better :)
