### ISSUE TITLE
Running a pair of commands on enter/exit of a directory.

### ISSUE THREAD

**Issue by hartzell** [zimbatm/direnv#165]
At work, we use [environment modules](http://en.wikipedia.org/wiki/Environment_Modules_%28software%29) to set up various environments.

I'd like to be able to execute `module load something otherthing` when I enter a directory and the corresponding `module unload something otherthing` when I leave.

Is there some nice clean way to hook up a pair of commands?

**Comment by zimbatm** [comment]
Nice, I didn't know about environment modules. How does it transfer the environment variables to the shell ? Probably a hook of some sort but I didn't find anything in the doc.

The `.envrc` is evaluated by a bash sub-shell so it should be possible to use `moduel load something otherthing` in it. `module unload` would be automatic once you exit the directory (if I understand what it's doing well).

**Comment by hartzell** [comment]
The details are shell dependent, but generally the "module" command that a user types is something like an alias or function that runs a command ("modulecmd") that translates the shell-agnostic module file into shell specific commands to manipulate the environment and that output is then eval'ed in to the running shell.  The original modules system (John Furlanit, et al.) is a bit long in the tooth, apparently [Lmod](https://www.tacc.utexas.edu/research-development/tacc-projects/lmod) is the thing to use in this space.

That should all sound very familiar to you.

I think of load and unload as a pair of commands and it didn't occur to me that when direnv resets the environment when on moves out of a directory it resets *everything*.  That's not quite the same thing as running `module unload`, but a quick test suggests that the end result seems to be the same (or close enough).  Since the list of loaded modules is stored in the environment, even that seems to be restored.

Hmmm.  I guess that we can close this....

**Comment by zimbatm** [comment]
Sweet, do you mind adding an entry on the wiki on how you did it ? https://github.com/zimbatm/direnv/wiki#tools-integration

**Comment by zimbatm** [comment]
Note that only environment variables that are touched by the `.envrc` are restored so it might compete with other invocations of `module load`

**Comment by hartzell** [comment]
Well, so far I haven't *done* anything beyond adding the line 

    module add NAME_OF_A_MODULEFILE

 to my .envrc.  As you pointed out, things seem to be cleaned up appropriately.  I still feel a little bit like I'm getting away with something, but it seems to work, so....

Here's an example that loads our "apps/perl-modules/5.18.4" module, which sets up some stuff itself and then cascades to load its dependencies (e.g. Oracle setup):

```
% cd trunk/
direnv: loading .envrc
direnv: export +ORACLE_SID +PERL5LIB +PINTO_HOME +TNS_ADMIN ~LD_LIBRARY_PATH ~LOADEDMODULES ~MANPATH ~ORACLE_HOME ~PATH ~_LMFILES_
% cat .envrc
module load apps/perl-modules/5.18.4
% cd ..
direnv: unloading
% printenv TNS_ADMIN
```

**Comment by zimbatm** [comment]
Hmm, you didn't have to setup an alias or function before ? The base sub-shell is invoked with `--noprofile --norc` so it shouldn't pick up anything from the `~/.bashrc`

**Comment by hartzell** [comment]
Ah.  Yes, there is a standard configuration that one uses to set up the environment modules system.

The details very depending on which generation of the modules system one is using, e.g. [the original](http://modules.sourceforge.net/) or [Lmod](https://github.com/TACC/Lmod) and vary depending on how it is installed onto the system.  Each system should have instructions.

Without going into the details of how it is set up here at work, one ends up with something like this:

```
module () {  eval `/yada/yada/hey/bin/modulecmd bash $*`
}
```

and running e.g. `module load apps/something` spits out the appropriate set of export statements which get eval'ed into the current shell environment.

**But**, I've done nothing special to get it to interact with [direnv](http://direnv.net).  So far it's just working.

**Comment by zimbatm** [comment]
Okay, thanks for the clarifications. I suspect we're missing a `--nodontloadanythingoforreal` flag to force bash to be pristine.
