### ISSUE TITLE
Using direnv with rake

### ISSUE THREAD

**Issue by kiddrew** [zimbatm/direnv#168]
Sorry if this has been asked, but I couldn't find it.  I have an rspec test that requires a certain environment variable to be set.  The test passed when the variable was global, but it's not working now that I'm using direnv.  Has anyone solved this?

**Comment by zimbatm** [comment]
No worries. Is rake invoked from the shell or from another program ?

* bash (with direnv) -> rake
* IDE / Other programe (without direnv) -> rake

**Comment by kiddrew** [comment]
I've tried running rake directly from the command line and using guard, which I think is the same thing.  neither works.

**Comment by zimbatm** [comment]
Hmm, what is the error you're getting ? The only difference I can think of is that the environment variable value would not be the same somehow. Try printing it and see if it's correct.

**Comment by kiddrew** [comment]
I'm not getting an error - it's just not using the file, so the environment variables aren't getting set.

**Comment by zimbatm** [comment]
Did you export the environment variable in the .envrc ?

It should look like:
```
export MY_ENV=foobar
```

**Comment by kiddrew** [comment]
Found my issue - I missed a setup step.  False alarm.  User error.  =)

**Comment by zimbatm** [comment]
Glad you found it !
